version: '3.4'

x-logging-config: &logging-config
  logging:
    driver: 'local'

services:
  frontend:
    image: openeduhub/oeh-search-frontend:${FRONTEND_RELEASE}
    <<: *logging-config
    environment:
      - WORDPRESS_URL=${WORDPRESS_URL?}
      - EDU_SHARING_API_URL=${EDUSHARING_URL?}/rest
      - SHOW_EXPERIMENTS=${SHOW_EXPERIMENTS}
    ports:
      - '127.0.0.1:${FRONTEND_PORT?}:80'
    restart: always
  analytics:
    image: openeduhub/oeh-search-analytics:${ANALYTICS_RELEASE}
    <<: *logging-config
    environment:
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL?}
      - EDUSHARING_URL=${EDUSHARING_URL?}
    ports:
      - '127.0.0.1:${ANALYTICS_PORT?}:3000'
    restart: always
